require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/LineLength:
  Max: 80

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

RSpec/AnyInstance:
  Enabled: false

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
